USE HOSPITAL;

CREATE TABLE PAITENT(
PAITENT_ID VARCHAR(20) PRIMARY KEY,
NAME VARCHAR(50),
DOB DATE,
AGE INT,
CITY VARCHAR(50),
CONTACT varchar(20), 
GENDER varchar(20), 
Department varchar(50), 
DOCTORS varchar(50)
);

SELECT * FROM PAITENT;

UPDATE PAITENT
SET PAITENT_ID = CONCAT('KDAH100104', REPLACE(Paitent_id,'KDAH',''));